all:
  children:
    crc_hosts:
      hosts:
        crc01:
          ansible_host: 192.168.10.55
          ansible_user: lab
          crc_cluster_name: crc01
          crc_bind_address: 192.168.10.55
        crc02:
          ansible_host: 192.168.10.56
          ansible_user: lab
          crc_cluster_name: crc02
          crc_bind_address: 192.168.10.56
        crc03:
          ansible_host: 192.168.10.61
          ansible_user: lab
          crc_cluster_name: crc03
          crc_bind_address: 192.168.10.61
