---
- name: Configure CRC DNS records
  hosts: crc_hosts
  gather_facts: false
  tags: technitium_dns

  roles:
    - role: technitium_dns
      tags: technitium_dns

- name: Install and expose OpenShift CRC
  hosts: crc_hosts
  become: true
  gather_facts: true
  tags: crc_local

  roles:
    - role: crc_local
      tags: crc_local
